SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Models/GamePitching.cs
// ***********************************************************************
// Assembly         : 
// Author           : S525033
// Created          : 11-18-2016
//
// Last Modified By : S525033
// Last Modified On : 11-18-2016
// ***********************************************************************
// <copyright file="GamePitching.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;

namespace SportsPrediction_NW_Baseball.Models
{
    /// <summary>
    /// Class GamePitching.
    /// </summary>
    public class GamePitching
{
        /// <summary>
        /// Gets or sets the game pitching identifier.
        /// </summary>
        /// <value>The game pitching identifier.</value>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Key]
    public int GamePitchingID { get; set; }
        /// <summary>
        /// Gets or sets the matchdate.
        /// </summary>
        /// <value>The matchdate.</value>
        public string Matchdate { get; set; }
        /// <summary>
        /// Gets or sets the opponent.
        /// </summary>
        /// <value>The opponent.</value>
        public string Opponent  { get; set; }
        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        /// <value>The status.</value>
        public string Status { get; set; }
        /// <summary>
        /// Gets or sets the innings pitched.
        /// </summary>
        /// <value>The innings pitched.</value>
        public double InningsPitched { get; set; }
        /// <summary>
        /// Gets or sets the hits.
        /// </summary>
        /// <value>The hits.</value>
        public int Hits { get; set; }
        /// <summary>
        /// Gets or sets the runs.
        /// </summary>
        /// <value>The runs.</value>
        public int Runs { get; set; }
        /// <summary>
        /// Gets or sets the earned runs.
        /// </summary>
        /// <value>The earned runs.</value>
        public int EarnedRuns { get; set; }
        /// <summary>
        /// Gets or sets the walk.
        /// </summary>
        /// <value>The walk.</value>
        public int Walk { get; set; }
        /// <summary>
        /// Gets or sets the strikeouts.
        /// </summary>
        /// <value>The strikeouts.</value>
        public int Strikeouts { get; set; }
        /// <summary>
        /// Gets or sets the double.
        /// </summary>
        /// <value>The double.</value>
        public int Double { get; set; }
        /// <summary>
        /// Gets or sets the triple.
        /// </summary>
        /// <value>The triple.</value>
        public int Triple { get; set; }
        /// <summary>
        /// Gets or sets the home runs.
        /// </summary>
        /// <value>The home runs.</value>
        public int HomeRuns { get; set; }
        /// <summary>
        /// Gets or sets the wild pitches.
        /// </summary>
        /// <value>The wild pitches.</value>
        public int WildPitches { get; set; }
        /// <summary>
        /// Gets or sets the balks.
        /// </summary>
        /// <value>The balks.</value>
        public int Balks { get; set; }
        /// <summary>
        /// Gets or sets the hit by pitch.
        /// </summary>
        /// <value>The hit by pitch.</value>
        public int HitByPitch { get; set; }
        /// <summary>
        /// Gets or sets the intentional walk.
        /// </summary>
        /// <value>The intentional walk.</value>
        public int IntentionalWalk { get; set; }
        /// <summary>
        /// Gets or sets the score.
        /// </summary>
        /// <value>The score.</value>
        public string Score { get; set; }
        /// <summary>
        /// Gets or sets the wins.
        /// </summary>
        /// <value>The wins.</value>
        public int Wins { get; set; }
        /// <summary>
        /// Gets or sets the losses.
        /// </summary>
        /// <value>The losses.</value>
        public int Losses { get; set; }
        /// <summary>
        /// Gets or sets the saves.
        /// </summary>
        /// <value>The saves.</value>
        public int Saves { get; set; }
        /// <summary>
        /// Gets or sets the earned run average.
        /// </summary>
        /// <value>The earned run average.</value>
        public double EarnedRunAverage { get; set; }
        /// <summary>
        /// Gets or sets the season.
        /// </summary>
        /// <value>The season.</value>
        public string Season { get; set; }
        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        /// <value>The type.</value>
        public string Type { get; set; }

        /// <summary>
        /// Reads all from CSV.
        /// </summary>
        /// <param name="filepath">The filepath.</param>
        /// <returns>List&lt;GamePitching&gt;.</returns>
        public static List<GamePitching> ReadAllFromCSV(string filepath)
        {
            List<GamePitching> lst = File.ReadAllLines(filepath)
                                         .Skip(1)
                                         .Select(v => GamePitching.OneFromCsv(v))
                                         .ToList();
            return lst;
        }

        /// <summary>
        /// Called when [from CSV].
        /// </summary>
        /// <param name="csvLine">The CSV line.</param>
        /// <returns>GamePitching.</returns>
        public static GamePitching OneFromCsv(string csvLine)
        {
            string[] values = csvLine.Split(',');
            GamePitching item = new GamePitching();
            int i = 0;
            item.GamePitchingID = Convert.ToInt32(values[i++]);
            item.Matchdate = Convert.ToString(values[i++]);
            item.Opponent = Convert.ToString(values[i++]);
            item.Status = Convert.ToString(values[i++]);
            item.InningsPitched = Convert.ToDouble(values[i++]);
            item.Hits = Convert.ToInt32(values[i++]);
            item.Runs = Convert.ToInt32(values[i++]);
            item.EarnedRuns = Convert.ToInt32(values[i++]);
            item.Walk = Convert.ToInt32(values[i++]);
            item.Strikeouts = Convert.ToInt32(values[i++]);
            item.Double = Convert.ToInt32(values[i++]);
            item.Triple = Convert.ToInt32(values[i++]);
            item.HomeRuns = Convert.ToInt32(values[i++]);
            item.WildPitches = Convert.ToInt32(values[i++]);
            item.Balks = Convert.ToInt32(values[i++]);
            item.HitByPitch = Convert.ToInt32(values[i++]);
            item.IntentionalWalk = Convert.ToInt32(values[i++]);
            item.Score = Convert.ToString(values[i++]);
            item.Wins = Convert.ToInt32(values[i++]);
            item.Losses = Convert.ToInt32(values[i++]);
            item.Saves = Convert.ToInt32(values[i++]);
            item.EarnedRunAverage = Convert.ToDouble(values[i++]);
            item.Season = Convert.ToString(values[i++]);
            item.Type = Convert.ToString(values[i++]);

            //Console.WriteLine(item);
            return item;
        }
}

}

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Controllers/GamePitchingsController.cs
// ***********************************************************************
// Assembly         : 
// Author           : S525033
// Created          : 11-18-2016
//
// Last Modified By : S525033
// Last Modified On : 11-18-2016
// ***********************************************************************
// <copyright file="GamePitchingsController.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using SportsPrediction_NW_Baseball.Models;
using System;
using System.Collections.Generic;

namespace SportsPrediction_NW_Baseball.Controllers
{
    /// <summary>
    /// Class GamePitchingsController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNet.Mvc.Controller" />
    public class GamePitchingsController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private ApplicationDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="GamePitchingsController" /> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public GamePitchingsController(ApplicationDbContext context)
        {
            _context = context;    
        }


        // GET: search by season,opponent to yield game statistics.
        /// <summary>
        /// Games es the specified search string.
        /// </summary>
        /// <param name="SearchString">The search string.</param>
        /// <param name="year">The year.</param>
        /// <param name="typesel">The typesel.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Games(string SearchString, string year, string typesel)
        {
            ViewBag.SearchString = SearchString;
            ViewBag.bat = null;
            ViewBag.pitch = null;
            ViewBag.pitchs = null;
            ViewBag.nams = null;
            ViewBag.nam = null;

            //generic object
            List<object> mymodel = new List<object>();

            //drop down list populating for years.
            var yearlist = new List<String>();

            var years = from m in _context.GamePitchings
                        orderby m.Season descending
                        select m.Season;

            yearlist.AddRange(years.Distinct());

            ViewBag.year = new SelectList(yearlist);

            //type populating.
            var types = new List<String>();
            types.Add("Pitching");
            types.Add("Batting");

            ViewBag.typesel = new SelectList(types);

            //search operations
            var pitchings = from m in _context.GamePitchings
                            select m;

            var battings = from m in _context.GameBattings
                           select m;

            //search based on the type,year and opponent name is not entered. 
            if (String.IsNullOrEmpty(SearchString) && !String.IsNullOrEmpty(year) && !String.IsNullOrEmpty(typesel))
            {
                if (typesel == "Batting")
                {
                    battings = battings.Where(s => s.Season == year);
                    mymodel.Add(battings);
                    ViewBag.bat = battings;
                    return View(mymodel);
                }

                if (typesel == "Pitching")
                {
                    pitchings = pitchings.Where(s => s.Season == year);
                    mymodel.Add(pitchings);
                    ViewBag.pitch = pitchings;
                    return View(mymodel);
                }
            }

            //search based on the type,year and opponent name selected. 
            if (!String.IsNullOrEmpty(SearchString) || !String.IsNullOrEmpty(year) || !String.IsNullOrEmpty(typesel))
            {
                if (typesel == "Batting")
                {
                    battings = battings.Where(s => (s.Opponent.Contains(SearchString)) && (s.Season == year));
                    var cnt = battings.Count();
                    if (cnt != 0)
                    {
                        mymodel.Add(battings);
                        ViewBag.bat = battings;
                        return View(mymodel);
                    }
                    else
                    {
                        ViewBag.bat = null;
                        ViewBag.nam = "noresult";
                        return View(mymodel);
                    }
                }

                if (typesel == "Pitching")
                {
                    pitchings = pitchings.Where(s => (s.Opponent.Contains(SearchString)) && (s.Season == year));
                    var cnt = pitchings.Count();
                    if (cnt != 0)
                    {
                        mymodel.Add(pitchings);
                        ViewBag.pitch = pitchings;
                        return View(mymodel);
                    }
                    else
                    {
                        ViewBag.pitch = null;
                        ViewBag.nams = "noresult";
                        return View(mymodel);
                    }
                }
            }

            //default data to be displayed on the view initially.
            var pitchingss = from m in _context.GamePitchings
                             select m;

            pitchingss = pitchingss.Where(s => (s.Type == types[0]) && (s.Season == yearlist[0]));

            mymodel.Add(pitchingss);
            ViewBag.pitchs = pitchingss;
            return View(mymodel);
        }

        //populating the statics of the game after clicking on the more statistics.
        /// <summary>
        /// Games the batting stats.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult GameBattingStats(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            GameBatting gamebatting = _context.GameBattings.Single(m => m.GameBattingID == id);
            if (gamebatting == null)
            {
                return HttpNotFound();
            }

            return View(gamebatting);
        }

        //populating the statics of the game after clicking on the more statistics.
        /// <summary>
        /// Games the pitching stats.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult GamePitchingStats(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            GamePitching gamepitching = _context.GamePitchings.Single(m => m.GamePitchingID == id);
            if (gamepitching == null)
            {
                return HttpNotFound();
            }

            return View(gamepitching);
        }


        // GET: Player Pitching view to search by match date and type of statistics also.
        /// <summary>
        /// Games the pitching.
        /// </summary>
        /// <param name="SearchString">The search string.</param>
        /// <param name="typesel">The typesel.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult GamePitching(string SearchString, string typesel)
        {
            ViewBag.SearchString = SearchString;
            ViewBag.nam = null;
            //search operations
            var pitchss = from m in _context.GamePitchings
                          select m;

            var batss = from m in _context.GameBattings
                        select m;

            //type populating.
            var types = new List<string>();
            types.Add("All Statistics");
            types.Add("Pitching");
            types.Add("Batting");

            ViewBag.typesel = new SelectList(types);

            //search based on the date entered.
            if (!String.IsNullOrEmpty(SearchString) && !String.IsNullOrEmpty(typesel))
            {
                var x = SearchString;
                if (x.Length == 10)
                {
                    var d = string.Concat(x.Substring(0, 6), x.Substring(8, 2));


                    if (typesel == "All Statistics")
                    {
                        pitchss = pitchss.Where(s => (s.Matchdate == d));
                        var row = pitchss.Count();

                        batss = batss.Where(s => (s.Matchdate == d));
                        var row1 = batss.Count();

                        if (row != 0 && row1 != 0)
                        {
                            ViewBag.nam = pitchss;
                            ViewBag.bat = batss;
                            return View(pitchss);
                        }
                        else
                        {
                            ViewBag.nam = null;
                            ViewBag.bat = null;
                            ViewBag.nams = "noresult";
                        }
                    }


                    if (typesel == "Pitching")
                    {
                        pitchss = pitchss.Where(s => (s.Matchdate == d));
                        var row = pitchss.Count();

                        if (row != 0)
                        {
                            ViewBag.nam = pitchss;
                            return View(pitchss);
                        }
                        else
                        {
                            ViewBag.nam = null;
                            ViewBag.nams = "noresult";
                        }
                    }

                    if (typesel == "Batting")
                    {
                        batss = batss.Where(s => (s.Matchdate == d));
                        var row = batss.Count();

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/GamePitchings/Delete.cshtml
@model SportsPrediction_NW_Baseball.Models.GamePitching

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GamePitching</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Balks)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Balks)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Double)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Double)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EarnedRunAverage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EarnedRunAverage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EarnedRuns)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EarnedRuns)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HitByPitch)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HitByPitch)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Hits)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hits)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomeRuns)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomeRuns)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InningsPitched)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InningsPitched)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IntentionalWalk)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IntentionalWalk)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Losses)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Losses)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Matchdate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Matchdate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Opponent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opponent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Runs)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Runs)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Saves)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Saves)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Season)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Season)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Strikeouts)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Strikeouts)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Triple)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Triple)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Walk)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Walk)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.WildPitches)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WildPitches)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Wins)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Wins)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/GamePitchings/Games.cshtml
@model IEnumerable<object>

<div class="text-center">
    <h2>Game Statistics</h2>
</div>

<p>
    @using (Html.BeginForm("Games", "GamePitchings", FormMethod.Get))
    {
    <p>
        <div class="row">
            <div class="col-md-2">
                Select Type : @Html.DropDownList("typesel")
            </div>
            <div class="col-md-2">
                Select Year : @Html.DropDownList("year")
            </div>
        </div>
        <br />
        <div class="form-group">
            <label class="col-md-2 control-label">Search by Opponent name</label>
            <div class="col-md-3 inputGroupContainer">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                    <input type='text' name='SearchString' value= "@((string)ViewBag.SearchString)" placeholder="Opponent name" class="form-control" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success">GO</button>
            </div>
        </div>
        <br />
        <br />
    </p>
    }
    </p>
    <br /><br />

    @if (ViewBag.bat != null)
    {
        <table class="table">
            <tr>
            <tr>
                <th>
                    Matchdate
                </th>
                <th>
                    Opponent
                </th>
                <th>
                    Runs
                </th>
                <th>
                    RunsBattedIn
                </th>
                <th>
                    Season
                </th>
                <th>
                    Status
                </th>
                <th>
                    AtBat
                </th>
                <th>
                    Avg
                </th>
                <th>
                    CaughtStealing
                </th>
                <th>
                    Hits
                </th>
                <th>
                    HomeRuns
                </th>
                <th></th>
            </tr>

            @foreach (var item in ViewBag.bat)
            {
                <tr>
                    <th>
                        @item.Matchdate
                    </th>
                    <th>
                        @item.Opponent
                    </th>
                    <th>
                        @item.Runs
                    </th>
                    <th>
                        @item.RunsBattedIn
                    </th>
                    <th>
                        @item.Season
                    </th>
                    <th>
                        @item.Status
                    </th>
                    <th>
                        @item.AtBat
                    </th>
                    <th>
                        @item.Avg
                    </th>
                    <th>
                        @item.CaughtStealing
                    </th>
                    <th>
                        @item.Hits
                    </th>
                    <th>
                        @item.HomeRuns
                    </th>
                    <th>
                        <a asp-action="GameBattingStats" asp-route-id="@item.GameBattingID">MoreStatistics</a>
                    </th>
                </tr>
            }
        </table>
    }

    @if (ViewBag.pitch != null)
    {
        <table class="table">
            <tr>
                <th>
                    Matchdate
                </th>
                <th>
                    Opponent
                </th>
                <th>
                    Status
                </th>
                <th>
                    Hits
                </th>
                <th>
                    HomeRuns
                </th>
                <th>
                    InningsPitched
                </th>
                <th>
                    Losses
                </th>
                <th>
                    Runs
                </th>
                <th>
                    Score
                </th>
                <th>
                    Season
                </th>
                <th>
                    Wins
                </th>
                <th></th>
            </tr>

            @foreach (var item in ViewBag.pitch)
            {
                <tr>
                    <th>
                        @item.Matchdate
                    </th>
                    <th>
                        @item.Opponent
                    </th>
                    <th>
                        @item.Status
                    </th>
                    <th>
                        @item.Hits
                    </th>
                    <th>
                        @item.HomeRuns
                    </th>
                    <th>
                        @item.InningsPitched
                    </th>
                    <th>
                        @item.Losses
                    </th>
                    <th>
                        @item.Runs
                    </th>
                    <th>
                        @item.Score
                    </th>
                    <th>
                        @item.Season
                    </th>
                    <th>
                        @item.Wins
                    </th>
                    <th>
                        <a asp-action="GamePitchingStats" asp-route-id="@item.GamePitchingID">MoreStatistics</a>
                    </th>
                </tr>
            }
        </table>
    }

    @if (ViewBag.pitchs != null)
    {
        List<SportsPrediction_NW_Baseball.Models.GamePitching> lstfield = Model.ToList()[0] as List<SportsPrediction_NW_Baseball.Models.GamePitching>;

        <table class="table">
            <tr>
                <th>
                    Matchdate
                </th>
                <th>
                    Opponent
                </th>
                <th>
                    Status
                </th>
                <th>
                    Hits
                </th>
                <th>
                    HomeRuns
                </th>
                <th>
                    InningsPitched
                </th>
                <th>
                    Losses
                </th>
                <th>
                    Runs
                </th>
                <th>
                    Score
                </th>
                <th>
                    Season
                </th>
                <th>
                    Wins
                </th>
                <th></th>
            </tr>

            @foreach (var item in ViewBag.pitchs)
            {
                <tr>
                    <th>
                        @item.Matchdate
                    </th>
                    <th>
                        @item.Opponent
                    </th>
                    <th>
                        @item.Status
                    </th>
                    <th>
                        @item.Hits
                    </th>
                    <th>
                        @item.HomeRuns
                    </th>
                    <th>
                        @item.InningsPitched
                    </th>
                    <th>
                        @item.Losses
                    </th>
                    <th>
                        @item.Runs
                    </th>
                    <th>
                        @item.Score
                    </th>
                    <th>
                        @item.Season
                    </th>
                    <th>
                        @item.Wins
                    </th>
                    <th>
                        <a asp-action="GamePitchingStats" asp-route-id="@item.GamePitchingID">MoreStatistics</a>
                    </th>
                </tr>
            }
        </table>
    }

    @if (ViewBag.nams == "noresult")
    {
        <div class="alert alert-warning">
            <strong>Your search did not yield any results.!! </strong>
        </div>
    }

    @if (ViewBag.nam == "noresult")
    {
        <div class="alert alert-warning">
            <strong>Your search did not yield any results!! </strong>
        </div>
    }