SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Controllers/PlayerBattingsController.cs
// ***********************************************************************
// Assembly         : 
// Author           : S525033
// Created          : 11-18-2016
//
// Last Modified By : S525033
// Last Modified On : 11-18-2016
// ***********************************************************************
// <copyright file="PlayerBattingsController.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using SportsPrediction_NW_Baseball.Models;
using System;
using System.Collections.Generic;

namespace SportsPrediction_NW_Baseball.Controllers
{
    /// <summary>
    /// Class PlayerBattingsController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNet.Mvc.Controller" />
    public class PlayerBattingsController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private ApplicationDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerBattingsController"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public PlayerBattingsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        //// GET: Player Batting view.
        //public IActionResult Battings(string sortOrder, string SearchString, string year)
        //{
        //    //ViewBag.CurrentSort = sortOrder;
        //    //ViewBag.CurrentSort = sortOrder;
        //    ViewBag.playerNumberSort = String.IsNullOrEmpty(sortOrder) ? "player_desc" : "";
        //    ViewBag.nameSort = sortOrder == "Name" ? "name_desc" : "Name";

        //    ViewBag.CurrentFilter = SearchString;

        //    //drop down list populating for year
        //    var yearlist = new List<string>();

        //    var years = from m in _context.PlayerBattings
        //                orderby m.Year descending
        //                select m.Year;

        //    ViewBag.year = new SelectList(years.Distinct());

        //    //search operations
        //    var players = from m in _context.PlayerBattings
        //                  select m;

        //    //var flag = false;
        //    if (!String.IsNullOrEmpty(SearchString))
        //    {
        //        players = players.Where(s => (s.Name.Contains(SearchString) && s.Year == year));
        //        return View(players);
        //    }

        //    if (!String.IsNullOrEmpty(year))
        //    {
        //        players = players.Where(s => (s.Year == year));
        //        return View(players);
        //    }

        //    //sort based on the sort parameter
        //    switch (sortOrder)
        //    {
        //        //var y = year;
        //        case "player_desc":
        //            //players = players.Where(s => (s.Year == year));
        //            players = players.OrderByDescending(s => s.PlayerNumber);
        //            break;
        //        case "Name":
        //            //players = players.Where(s => (s.Year == year));
        //            players = players.OrderBy(s => s.Name);
        //            break;
        //        case "name_desc":
        //            //players = players.Where(s => (s.Year == year));
        //            players = players.OrderByDescending(s => s.Name);
        //            break;
        //        default:
        //            //players = players.Where(s => (s.Year == year));
        //            players = players.OrderBy(s => s.PlayerNumber);
        //            break;
        //    }

        //    return View(players);
        //}


        // GET: Player Batting view.
        /// <summary>
        /// Battings the specified sort order.
        /// </summary>
        /// <param name="sortOrder">The sort order.</param>
        /// <param name="SearchString">The search string.</param>
        /// <param name="year">The year.</param>
        /// <param name="sortType">Type of the sort.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Batting(string sortOrder, string SearchString, string year, string sortType)
        {
            ViewBag.noresult = null;
            ViewBag.playerNumberSort = String.IsNullOrEmpty(sortOrder) ? "player_desc" : "";
            ViewBag.nameSort = sortOrder == "Name" ? "name_desc" : "Name";

            //drop down list populating for year
            var yearlist = new List<string>();

            var years = from m in _context.PlayerBattings
                        orderby m.Year descending
                        select m.Year;

            yearlist.AddRange(years.Distinct());
            ViewBag.year = new SelectList(yearlist);

            //drop down list populating for sortType
            var sortlist = new List<string>();

            sortlist.Add("PlayerNumber");
            //sortlist.Add("Name");
            sortlist.Add("Hits");
            sortlist.Add("HomeRun");
            sortlist.Add("Runs");
           
            ViewBag.sortType = new SelectList(sortlist);

            //search operations
            var players = from m in _context.PlayerBattings
                          select m;

            if (!String.IsNullOrEmpty(SearchString))
            {
                players = players.Where(s => (s.Name.Contains(SearchString) && s.Year == year));
                var count = players.Count();
                if (count != 0)
                {
                    //sort based on the sort parameter
                    switch (sortType)
                    {
                        case "PlayerNumber":
                            players = players.Where(s => (s.Name.Contains(SearchString) && s.Year == year)).OrderBy(s => s.PlayerNumber);
                            break;
                        case "Hits":
                            players = players.Where(s => (s.Name.Contains(SearchString) && s.Year == year)).OrderByDescending(s => s.Hits);
                            break;
                        case "HomeRun":
                            players = players.Where(s => (s.Name.Contains(SearchString) && s.Year == year)).OrderByDescending(s => s.HomeRun);
                            break;
                        default:
                            players = players.Where(s => (s.Name.Contains(SearchString) && s.Year == year)).OrderByDescending(s => s.Runs);
                            break;
                    }
                   
                    return View(players);
                }
                else
                {
                    ViewBag.noresult = "noresult";
                    return View(players);
                }
            }

            if (!String.IsNullOrEmpty(year) && !String.IsNullOrEmpty(sortType))
            {
                switch (sortType)
                {
                    case "PlayerNumber":
                        players = players.Where(s => (s.Year == year)).OrderBy(s => s.PlayerNumber);
                        break;
                    case "Hits":
                        players = players.Where(s => (s.Year == year)).OrderByDescending(s => s.Hits);
                        break;
                    case "HomeRun":
                        players = players.Where(s => (s.Year == year)).OrderByDescending(s => s.HomeRun);
                        break;
                    default:
                        players = players.Where(s => (s.Year == year)).OrderByDescending(s => s.Runs);
                        break;
                }

                return View(players);
            }

            //default data to be displayed on the view initially.
            var battingss = from m in _context.PlayerBattings
                            select m;

            battingss = battingss.Where(s => (s.Year == yearlist[0])).OrderBy(s=> s.PlayerNumber);
            ViewBag.defualt = battingss;
            return View(battingss);
        }


        /// <summary>
        /// Fieldings the specified sort order.
        /// </summary>
        /// <param name="sortOrder">The sort order.</param>
        /// <param name="SearchString">The search string.</param>
        /// <param name="year">The year.</param>
        /// <param name="sortType">Type of the sort.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Fielding(string sortOrder, string SearchString, string year, string sortType)
        {
            ViewBag.noresult = null;

            //drop down list populating for year
            var yearlist = new List<string>();

            var years = from m in _context.PlayerFieldings
                        orderby m.Year descending
                        select m.Year;

            yearlist.AddRange(years.Distinct());
            ViewBag.year = new SelectList(yearlist);

            //drop down list populating for sortType
            var sortlist = new List<string>();

            sortlist.Add("PlayerNumber");
            sortlist.Add("Assist");
            sortlist.Add("DoublePlay");
            sortlist.Add("Putout");

            ViewBag.sortType = new SelectList(sortlist);

            //search operations
            var players = from m in _context.PlayerFieldings
                          select m;

            if (!String.IsNullOrEmpty(SearchString))
            {
                players = players.Where(s => (s.PlayerName.Contains(SearchString) && s.Year == year));
                var count = players.Count();
                if (count != 0)
                {
                    //sort based on the sort parameter
                    switch (sortType)
                    {
                        case "PlayerNumber":

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Controllers/PlayersController.cs
// ***********************************************************************
// Assembly         : 
// Author           : S525033
// Created          : 11-18-2016
//
// Last Modified By : S525033
// Last Modified On : 11-18-2016
// ***********************************************************************
// <copyright file="PlayersController.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using SportsPrediction_NW_Baseball.Models;
using System.Threading.Tasks;
using System;
using Newtonsoft.Json;

namespace SportsPrediction_NW_Baseball.Controllers
{
    /// <summary>
    /// Class PlayersController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNet.Mvc.Controller" />
    public class PlayersController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private ApplicationDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayersController"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public PlayersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        /// <summary>
        /// Indexes the specified search string.
        /// </summary>
        /// <param name="searchString">The search string.</param>
        /// <param name="searchString1">The search string1.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Index(string searchString, string searchString1)
        {
            var playerName = from m in _context.Player
                             select m;

            if (!(String.IsNullOrEmpty(searchString) || String.IsNullOrEmpty(searchString1)))
            {
                playerName = playerName.Where(s => s.PlayerName.Contains(searchString));
            }
            string json = JsonConvert.SerializeObject(playerName);
            ViewData["jsondata"] = json;
            Console.WriteLine("ufhifhdziooooooooo", json);
            return View(await playerName.ToListAsync());
        }


        // GET: Players/Details/5
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Player player = _context.Player.Single(m => m.PlayerNumber == id);
            if (player == null)
            {
                return HttpNotFound();
            }

            return View(player);
        }

        // GET: Players/Create
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        /// <summary>
        /// Creates the specified player.
        /// </summary>
        /// <param name="player">The player.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Player.Add(player);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Players/Edit/5
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Player player = _context.Player.Single(m => m.PlayerNumber == id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        /// <summary>
        /// Edits the specified player.
        /// </summary>
        /// <param name="player">The player.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Update(player);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Players/Delete/5
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Player player = _context.Player.Single(m => m.PlayerNumber == id);
            if (player == null)
            {
                return HttpNotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Player player = _context.Player.Single(m => m.PlayerNumber == id);
            _context.Player.Remove(player);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/PlayerBattings/Batting.cshtml
@model IEnumerable<SportsPrediction_NW_Baseball.Models.PlayerBatting>

@{
    ViewData["Title"] = "Batting";
}

<div class="text-center">
<h2>Player Batting Statistics</h2>
</div>

<p>
    @using (Html.BeginForm("Batting", "PlayerBattings", FormMethod.Get))
    {
    <p>
        Year : @Html.DropDownList("year")<br/><br/>       
        Sort By : @Html.DropDownList("sortType")<br /><br />       
        Search By Player Name: @Html.TextBox("SearchString") <br /><br />
        <input type="submit" class="btn btn-info" value="Search" />
    </p>
    }
    </p>

@if (ViewBag.noresult != null)
{
    <div class="alert alert-warning">
        <strong>Your search did not yield any results.!! </strong>
    </div>
}
else
{
    <table class ="table">
        <tr>
            <th>
                PlayerName
            </th>
            <th>
                PlayerNumber
            </th>
            <th>
                Hits
            </th>
            <th>
               HomeRun
            </th>
            <th>
                Runs
            </th>
            <th>
                GamesPlayed
            </th>
            <th>
                GamesStarted
            </th>
            <th>
                TotalBases
            </th>
            <th>
                Year
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => item.Name)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.PlayerNumber)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Hits)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.HomeRun)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Runs)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.GamesPlayed)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.GamesStarted)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.TotalBases)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Year)
                </th>
                <th>                    
                    <a asp-action="BattingStatistics" asp-route-id="@item.BattingID">More Statistics</a> 
                </th>
            </tr>
        }

    </table>

}

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/PlayerBattings/BattingStatistics.cshtml
@model SportsPrediction_NW_Baseball.Models.PlayerBatting

 <div class="text-center">
    <h2>Batting Statistics</h2>
 </div>
             
<div>
    <a asp-action="Batting">Back to  Players Batting</a>
</div>

<style>
    table, th, td 
    {
        font-family: arial, sans-serif;
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td 
    {
        padding: 4px;
    }

    tr:nth-child(odd) 
    {
        background-color: #dddddd;
    }
</style>

<table style="width:20%">
    <tr>
        <th>Year</th>
        <td>@ViewData.Model.Year</td>
    </tr>
    <tr>
        <th>PlayerName</th>
        <td>@ViewData.Model.Name</td>
    </tr>
    <tr>
        <th>PlayerNumber</th>
        <td>@ViewData.Model.PlayerNumber</td>
    </tr>
    <tr>
        <th>AtBat</th>
        <td>@ViewData.Model.AtBat</td>
    </tr>
    <tr>
        <th>Average</th>
        <td>@ViewData.Model.Average</td>
    </tr>
    <tr>
        <th>Double</th>
        <td>@ViewData.Model.Double</td>
    </tr>
    <tr>
        <th>GamesPlayed</th>
        <td>@ViewData.Model.GamesPlayed</td>
    </tr>
    <tr>
        <th>GamesStarted</th>
        <td>@ViewData.Model.GamesStarted</td>
    </tr>
    <tr>
        <th>Hits</th>
        <td>@ViewData.Model.Hits</td>
    </tr>
    <tr>
        <th>Runs</th>
        <td>@ViewData.Model.Runs</td>
    </tr>
    <tr>
        <th>RunsBattedIn</th>
        <td>@ViewData.Model.RunsBattedIn</td>
    </tr>
    <tr>
        <th>StolenBase</th>
        <td>@ViewData.Model.StolenBase</td>
    </tr>
    <tr>
        <th>Triple</th>
        <td>@ViewData.Model.Triple</td>
    </tr>
    <tr>
        <th>TotalBases</th>
        <td>@ViewData.Model.TotalBases</td>
    </tr>
</table>





<br /><br /><br />

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/PlayerBattings/Delete.cshtml
@model SportsPrediction_NW_Baseball.Models.PlayerBatting

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlayerBatting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AtBat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AtBat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Average)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Average)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Double)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Double)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GamesPlayed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GamesPlayed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GamesStarted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GamesStarted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Hits)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hits)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomeRun)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomeRun)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlayerNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayerNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Runs)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Runs)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RunsBattedIn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RunsBattedIn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StolenBase)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StolenBase)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalBases)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalBases)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Triple)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Triple)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/PlayerBattings/Fielding.cshtml
@model IEnumerable<SportsPrediction_NW_Baseball.Models.PlayerFielding>

@{
    ViewData["Title"] = "Fielding";
}
<div class="text-center">
    <h2>Player Fielding Statistics</h2>
</div>

<p>
    @using (Html.BeginForm("Fielding", "Players", FormMethod.Get))
    {
    <p>
        Year : @Html.DropDownList("year")<br /><br />
        Sort By : @Html.DropDownList("sortType")<br /><br />       
        Search By Player Name: @Html.TextBox("SearchString") <br /><br />
        <input type="submit" class="btn btn-info" value="Search" />
    </p>
    }
</p>


 @if (ViewBag.noresult != null)
 {
    <div class="alert alert-warning">
        <strong>Your search did not yield any results.!! </strong>
    </div>
 }
 else
 {
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlayerName)
            @*@Html.ActionLink("Name", "Fielding", new { sortOrder = ViewBag.nameSort,year = ViewBag.years })*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerNumber)
           @*@Html.ActionLink("PlayerNumber", "Fielding", new { sortOrder = ViewBag.playerNumberSort })*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Assist)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DoublePlay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Putout)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.catcher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StolenBallsAttempted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PassedBall)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>
                @Html.DisplayFor(modelItem => item.PlayerName)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.PlayerNumber)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.Assist)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.DoublePlay)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.Putout)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.catcher)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.StolenBallsAttempted)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.PassedBall)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.Year)
            </th>
            <th>
                <a asp-action="FieldingStatistics" asp-route-id="@item.FieldingID">MoreStatistics</a> 
            </th>
        </tr>
    }
</table>
 }

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/PlayerBattings/Pitching.cshtml
@model IEnumerable<SportsPrediction_NW_Baseball.Models.PlayerPitching>

@{

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pitching</title>
</head>
<body>

<div class="text-center">
<h2>Player Pitching Statistics</h2>
</div>

<p>
    @using (Html.BeginForm("Pitching", "PlayerBattings", FormMethod.Get))
    {
    <p>
        Year : @Html.DropDownList("year")<br/><br/>       
        Sort By : @Html.DropDownList("sortType")<br /><br />    
        Search By Player Name: @Html.TextBox("SearchString") <br /><br />
        <input type="submit" class="btn btn-info" value="Search" />
    </p>
    }
    </p>

@if (ViewBag.noresult == "noresult")
{
    <div class="alert alert-warning">
        <strong>Your search did not yield any results.!! </strong>
    </div>
}
else
{
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlayerNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerName)
         </th>
        <th>
            @Html.DisplayNameFor(model => model.AtBat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EarnedRunAverage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeRun)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InningsPitched)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Runs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Double)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EarnedRuns)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model)
{
    <tr>
        <th>
            @Html.DisplayFor(modelItem => item.PlayerNumber)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.PlayerName)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.AtBat)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.EarnedRunAverage)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.HomeRun)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.InningsPitched)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.Runs)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.Double)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.EarnedRuns)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.Type)
        </th>
        <th>
            @Html.DisplayFor(modelItem => item.Year)
        </th>
        <th>
            <a asp-action="PitchingStatistics" asp-route-id="@item.PitchingID">More Statistics</a>
        </th>
    </tr>
}

</table>
}
</body>
</html>