SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Controllers/HomeController.cs
// ***********************************************************************
// Assembly         : 
// Author           : S525033
// Created          : 11-18-2016
//
// Last Modified By : S525033
// Last Modified On : 11-18-2016
// ***********************************************************************
// <copyright file="HomeController.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace SportsPrediction_NW_Baseball.Controllers
{
    /// <summary>
    /// Class HomeController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNet.Mvc.Controller" />
    public class HomeController : Controller
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Abouts this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        /// <summary>
        /// Contacts this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        /// <summary>
        /// Errors this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Error()
        {
            return View();
        }
        /// <summary>
        /// Why the with us.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult whyWithUs()
        {

            return View();
        }
        /// <summary>
        /// FAQs this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult faq()
        {
            return View();
        }
        /// <summary>
        /// Teams this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Team()
        {
            return View();
        }
        /// <summary>
        /// Constructions this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult construction()
        {
            return View();
        }
        /// <summary>
        /// Performances this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Performance()
        {
            return View();
        }
        /// <summary>
        /// Teams the performance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult TeamPerformance()
        {
            return View();
        }
        /// <summary>
        /// Progresses this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Progress()
        {
            return View();
        }
        /// <summary>
        /// Deletes this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Delete()
        {
            return View();
        }
        /// <summary>
        /// Galleries this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult gallery()
        {
            return View();
        }
        /// <summary>
        /// Rules this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Rules()
        {
            return View();
        }
        /// <summary>
        /// Seasons the playerruns.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult SeasonPlayerruns()
        {
            return View();
        }
        /// <summary>
        /// Player runs this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Playerruns()
        {
            return View();
        }
        /// <summary>
        /// Scores this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Scores()
        {
            return View();
        }
        /// <summary>
        /// Generates the visualization.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult generateVisualization()
        {
            return View();
        }
        /// <summary>
        /// Players era.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult PlayersERA()
        {
            return View();
        }
        /// <summary>
        /// NWSU opponents.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult NWSUopponents()
        {
            return View();
        }
        public IActionResult HeatMap()
        {
            return View();
        }
    }
}

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Controllers/RoastersController.cs
// ***********************************************************************
// Assembly         : 
// Author           : S525033
// Created          : 11-18-2016
//
// Last Modified By : S525033
// Last Modified On : 11-18-2016
// ***********************************************************************
// <copyright file="RoastersController.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using SportsPrediction_NW_Baseball.Models;
using System;

namespace SportsPrediction_NW_Baseball.Controllers
{
    /// <summary>
    /// Class RoastersController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNet.Mvc.Controller" />
    public class RoastersController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private ApplicationDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="RoastersController"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public RoastersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Roasters
        /// <summary>
        /// Indexes the specified sort order.
        /// </summary>
        /// <param name="sortOrder">The sort order.</param>
        /// <param name="searchString">The search string.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.LastNameSortParm = String.IsNullOrEmpty(sortOrder) ? "lastname" : "";
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(sortOrder) ? "firstname" : "";
            ViewBag.PositionSortParm = String.IsNullOrEmpty(sortOrder) ? "position" : "";
            var roasters = from s in _context.Roaster.ToList()
                             select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                roasters = roasters.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstName.Contains(searchString) || s.Position.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "firstname":
                    roasters = roasters.OrderByDescending(s => s.FirstName);
                    break;
                case "lastname":
                    roasters = roasters.OrderBy(s => s.LastName);
                    break;
                case "position":
                    roasters = roasters.OrderBy(s => s.Position);
                    break;
                default:
                    roasters = roasters.OrderBy(s => s.FirstName);
                    break;
            }
            return View(roasters.ToList());
        }

        // GET: Roasters/Details/5
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Roaster roaster = _context.Roaster.Single(m => m.RoasterID == id);
            if (roaster == null)
            {
                return HttpNotFound();
            }

            return View(roaster);
        }

        // GET: Roasters/Create
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roasters/Create
        /// <summary>
        /// Creates the specified roaster.
        /// </summary>
        /// <param name="roaster">The roaster.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Roaster roaster)
        {
            if (ModelState.IsValid)
            {
                _context.Roaster.Add(roaster);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roaster);
        }

        // GET: Roasters/Edit/5
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Roaster roaster = _context.Roaster.Single(m => m.RoasterID == id);
            if (roaster == null)
            {
                return HttpNotFound();
            }
            return View(roaster);
        }

        // POST: Roasters/Edit/5
        /// <summary>
        /// Edits the specified roaster.
        /// </summary>
        /// <param name="roaster">The roaster.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Roaster roaster)
        {
            if (ModelState.IsValid)
            {
                _context.Update(roaster);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roaster);
        }

        // GET: Roasters/Delete/5
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Roaster roaster = _context.Roaster.Single(m => m.RoasterID == id);
            if (roaster == null)
            {
                return HttpNotFound();
            }

            return View(roaster);
        }

        // POST: Roasters/Delete/5
        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Roaster roaster = _context.Roaster.Single(m => m.RoasterID == id);
            _context.Roaster.Remove(roaster);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/Contact.cshtml
<div class="container">
    <h3 class="text-center">Contact Us</h3>
    <p class="text-center"><em>We love to hear you!</em></p>
    <div class="row test">
        <div class="col-md-4">
            <p>Northwest Baseball </p>
            <p><span class="glyphicon glyphicon-map-marker"></span>Maryville, Missouri, US</p>
            <p><span class="glyphicon glyphicon-phone"></span>Phone: +1 6605280406</p>
            <p><span class="glyphicon glyphicon-envelope"></span>Email: helpdesk@nwmail.com</p>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-sm-6 form-group">
                    <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
                </div>
                <div class="col-sm-6 form-group">
                    <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
                </div>
            </div>
            <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea>
            <div class="row">
                <div class="col-md-12 form-group">
                    <!--<h1 class="text-center"><a href="#myModal" role="button" class="btn btn-primary btn-lg" data-toggle="modal">Contact Us</a></h1>-->

                    <button type="submit" class="btn btn-default" onClick="func()">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    #googleMap {
        width: 100%; /* Span the entire width of the screen */
        height: 400px; /* Set the height to 400 pixels */
        -webkit-filter: grayscale(100%);
        filter: grayscale(100%); /* Change the color of the map to black and white * /
    }
</style>

<div id="googleMap"></div>

<!-- Add Google Maps -->
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script>
    var myCenter = new google.maps.LatLng(40.3461, -94.8725);

function initialize() {
var mapProp = {
center:myCenter,
zoom:12,
scrollwheel:false,
draggable:false,
mapTypeId:google.maps.MapTypeId.ROADMAP
};

var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

var marker = new google.maps.Marker({
position:myCenter,
});

marker.setMap(map);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">We'll reach you as soon as possible</h3>
            </div>
            <div class="modal-body">
                <p>Thanks for Contacting us</p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            </div>
        </div>
    </div>
</div>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/Index.cshtml
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
       
    </ol>
    <div class="carousel-inner" role="listbox" style="align-content:center">
        <div class="item active">
            <img src="~/images/home_b.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption">
                <p style="font-size:70px;color:white">
                  
                    <a style="font-size:70px;color:white" asp-controller="Home" asp-action="Performance">
                        Visualize Players Performance.
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/home_a.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption">
                <p style="font-size:70px;color:white">
                    
                    <a style="font-size:70px;color:white" asp-controller="GamePitchings" asp-action="Games">
                        Most awaited 2015 results.
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/home_c.jpg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption">
                <p style="font-size:70px;color:white">
                   
                    <a style="font-size:70px;color:white" asp-controller="Roasters" asp-action="Index">
                        Northwest Baseball Top Players List.
                    </a>
                </p>
            </div>
        </div>
       
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>
    
 
   
           <div style="width:auto">
            <a href="http://www.accuweather.com/en/us/maryville-mo/64468/weather-forecast/334097" class="aw-widget-legal">

            </a>
                   <div id="awcc1459374354705" class="aw-widget-current" data-locationkey="334097" data-unit="f" data-language="en-us" data-useip="false" data-uid="awcc1459374354705"></div>
            
            <script type="text/javascript" src="http://oap.accuweather.com/launch.js"></script>
            
        </div>
 

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/NWSUopponents.cshtml
<head>
    <!-- Plotly.js -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>

    <div id="myDiv"><!-- Plotly chart will be drawn inside this DIV --></div>
    <script type="text/javascript">
        var batting = {
            x: ['2010', '2011', '2012', '2013', '2014', '2015'],
            y: [5, 3, 13, 2, 11, 1],
            name: 'Missouri Western',
            type: 'bar',


        };

        var pitching = {
            x: ['2010', '2011', '2012', '2013', '2014', '2015'],
            y: [15, 2, 3, 4, 7, 3],
            name: 'NWMSU',
            type: 'bar',

        };

        var data = [batting, pitching];

        var layout = {
            barmode: 'group',
            title: 'NWMSU runs vs Missouri Western runs'

        };

        Plotly.newPlot('myDiv', data, layout);
        function display(s1) {

            var s1 = document.getElementById(s1);

            if (s1.value == "1") {
                var batting = {
                    x: ['2010', '2011', '2012', '2013', '2014', '2015'],
                    y: [5, 3, 13,2,11,1],
                    name: 'Missouri Western',
                    type: 'bar',

                };

                var pitching = {
                    x: ['2010', '2011', '2012', '2013', '2014', '2015'],
                    y: [15, 2, 3, 4, 7, 3],
                    name: 'NWMSU',
                    type: 'bar',

                };

                var data = [batting, pitching];

                var layout = {
                    barmode: 'group',
                    title: 'NWMSU runs Vs Missouri Western runs'
                };

                Plotly.newPlot('myDiv', data, layout);

            }
            else if (s1.value == "2") {
                var batting = {
                    x: ['2010', '2011', '2012', '2013', '2014', '2015'],
                    y: [6, 6, 5, 6, 3, 7],
                    name: 'Pitsburg State',
                    type: 'bar',

                };

                var pitching = {
                    x: ['2010', '2011', '2012', '2013', '2014', '2015'],
                    y: [1, 5, 11, 11, 4, 2],
                    name: 'NWMSU',
                    type: 'bar',

                };

                var data = [batting, pitching];

                var layout = {
                    barmode: 'group',
                    title: 'NWMSU runs Vs Pitsburg State runs'
                };

                Plotly.newPlot('myDiv', data, layout);

            }
            else {
                var batting = {
                    x: ['2010', '2011', '2012', '2013', '2014', '2015'],
                    y: [1, 5, 11, 11, 4, 2],
                    name: 'Emporia state',
                    type: 'bar',

                };

                var pitching = {
                    x: ['2010', '2011', '2012', '2013', '2014', '2015'],
                    y: [6, 6, 5, 6, 3, 7],
                    name: 'NWMSU',
                    type: 'bar',

                };

                var data = [batting, pitching];

                var layout = {
                    xaxis: {
                        dtick:1,
                        tickcolor: '##FF0000'

                    },
                    yaxis: {


                        tickcolor: '#FF0000'
                    },
                    barmode: 'group',
                    title: 'NWMSU runs Vs Emporia state runs'

                };

                Plotly.newPlot('myDiv', data, layout);


            }
        }

    </script>

    <select id="slct" name="slct" onchange="display(this.id)">
        <option value="1">Missouri Western</option>
        <option value="2">Pitsburg State</option>
        <option value="3">Emporia state</option>
    </select>
</body>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/Performance.cshtml
    <link href="~/js/nv.d3.css" rel="stylesheet" type="text/css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>
    <script src="~/js/nv.d3.js"></script>
    <style>
        text {
            font: 34px sans-serif;
        }

        svg {
            display: block;
        }
       
    </style>
<h1>Players Performance</h1>
<br>
<br>
<body>
    <div id="chart1">
        <svg></svg>
    </div>
    <script>

    historicalBarChart = [
        {
            key: "Notenvergabe",
            values: [
                {
                    "label" : "Bob" ,
                    "value" : 29
                } ,
                {
                    "label" : "Jhon" ,
                    "value" : 15
                } ,
                {
                    "label" : "Rob" ,
                    "value" : 32
                } ,
                {
                    "label" : "Henry" ,
                    "value" : 17
                } ,
                {
                    "label" : "Smith" ,
                    "value" : 21
                } ,
                {
                    "label" : "Ben" ,
                    "value" : 69
                } ,
                {
                    "label" : "Mike" ,
                    "value" : 31
                } ,
                {
                    "label" : "Brain" ,
                    "value" : 51
                }
            ]
        }
    ];

    nv.addGraph(function() {
        var chart = nv.models.discreteBarChart()
            .x(function(d) { return d.label })
            .y(function(d) { return d.value })
            .staggerLabels(true)
            //.staggerLabels(historicalBarChart[0].values.length > 8)
            .showValues(true)
            .duration(250)
            ;

        d3.select('#chart1 svg')
            .datum(historicalBarChart)
            .call(chart);

        nv.utils.windowResize(chart.update);
        return chart;
    });

    </script>
</body>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/PlayersERA.cshtml
<head>
    <!--Plotly.js-->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <div class="showcase__section" id="bubble">
        <div class="spacer --small"></div>
        <div id="bubbleplots">
            <div class="bubbleplot" data-num="0">
                <div class="plot" id="plotdiv"></div>
                <div class="control-row">
                    Season: <select class="countrydata"></select>
                </div>
            </div>
        </div>
    </div>


    <script>
        /* JAVASCRIPT CODE GOES HERE */



        Plotly.d3.csv("http://" + window.location.host + "/Data/sep.csv", function (err, rows) {

            function unpack(rows, key) {
                return rows.map(function(row) { return row[key]; });
            }

            var allCountryNames = unpack(rows, 'country'),
                allYear = unpack(rows, 'year'),
                allGdp = unpack(rows, 'gdpPercap'),
                listofCountries = [],
                currentCountry,
                currentGdp = [],
                currentYear = [];

            for (var i = 0; i < allCountryNames.length; i++ ){
                if (listofCountries.indexOf(allCountryNames[i]) === -1 ){
                    listofCountries.push(allCountryNames[i]);
                }
            }

            function getCountryData(chosenCountry) {
                currentGdp = [];
                currentYear = [];
                for (var i = 0 ; i < allCountryNames.length ; i++){
                    if ( allCountryNames[i] === chosenCountry ) {
                        currentGdp.push(allGdp[i]);
                        currentYear.push(allYear[i]);
                    }
                }
            };

            // Default Country Data
            setBubblePlot('2016');

            function setBubblePlot(chosenCountry) {
                getCountryData(chosenCountry);


                var data = [
  {
      x: currentYear,
      y: currentGdp,
      type: 'bar',
      width: 0.2,

  }];



                var layout = {
                    title: 'Earned runs average of Players in  <br>' + chosenCountry ,
                    xaxis: {
                    dtick: 1,
                    tickcolor: '##FF0000'
                },
            yaxis: {


                tickcolor: '#FF0000'
            }
                };

                Plotly.newPlot('plotdiv', data, layout);
            };

            var innerContainer = document.querySelector('[data-num="0"'),
                plotEl = innerContainer.querySelector('.plot'),
                countrySelector = innerContainer.querySelector('.countrydata');

            function assignOptions(textArray, selector) {
                for (var i = 0; i < textArray.length;  i++) {
                    var currentOption = document.createElement('option');
                    currentOption.text = textArray[i];
                    selector.appendChild(currentOption);
                }
            }

            assignOptions(listofCountries, countrySelector);

            function updateCountry(){
                setBubblePlot(countrySelector.value);
            }

            countrySelector.addEventListener('change', updateCountry, false);
        });
    </script>
</body>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/Progress.cshtml
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>
    <script src="~/js/nv.d3.js"></script>
    <script src="~/js/stream_layers.js"></script>
   
    <svg id="test3" class="mypiechart"></svg>
    <script>

        var testdata3 = [
        { key: "Updated", y: 50 },
        { key: "Pending", y: 50 }
    ];

        var arcRadius3 = [
		{ inner: 0, outer: 1 },
		{ inner: 0, outer: 0.8 }
	];

        var height = 350;
        var width = 350;

        nv.addGraph(function () {
            var chart = nv.models.pieChart()
            .x(function (d) { return d.key })
            .y(function (d) { return d.y })
            .donut(true)
			.showLabels(true)
            .width(width)
            .height(height)
			.arcsRadius(arcRadius3)
			.donutLabelsOutside(true)
            .id('donut3'); // allow custom CSS for this one svg

            d3.select("#test3")
            .datum(testdata3)
            .transition().duration(1200)
            .attr('width', width)
            .attr('height', height)
            .call(chart);

            return chart;

        });
    </script>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/TeamPerformance.cshtml
    <link href="~/js/nv.d3.css" rel="stylesheet" type="text/css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>
    <script src="~/js/nv.d3.js"></script>
    <style>
        text {
            font: 12px sans-serif;
        }

        svg {
            display: block;
        }

    </style>
<h1>Weather Conditions</h1>
<br>
<br>
<br>
<br>
<br>
<br>
<body class='with-3d-shadow with-transitions'>
    <svg id="test1"></svg>
    <script>

    var chart;
    nv.addGraph(function() {
        chart = nv.models.historicalBarChart();
        chart
            .margin({left: 100, bottom: 100})
            .useInteractiveGuideline(true)
            .duration(250)
            ;

        // chart sub-models (ie. xAxis, yAxis, etc) when accessed directly, return themselves, not the parent chart, so need to chain separately
        chart.xAxis
            .axisLabel("Day");
            

        chart.yAxis
            .axisLabel('Temperature')
            .tickFormat(d3.format(',.2f'));

        chart.showXAxis(true);

        d3.select('#test1')
            .datum(sinData())
            .transition()
            .call(chart);

        nv.utils.windowResize(chart.update);
        chart.dispatch.on('stateChange', function(e) { nv.log('New State:', JSON.stringify(e)); });
        return chart;
    });

    //Simple test data generators
    function sinAndCos() {
        var sin = [],
            cos = [];

        for (var i = 0; i < 100; i++) {
            sin.push({x: i, y: Math.sin(i/10)});
            cos.push({x: i, y: .5 * Math.cos(i/10)});
        }

        return [
            {values: sin, key: "S", color: "#ff7f0e"},
            {values: cos, key: "C", color: "#2ca02c"}
        ];
    }

    function sinData() {
        var sin = [];

        for (var i = 0; i < 100; i++) {
            sin.push({x: i, y: Math.sin(i/10) * Math.random() * 10});
        }

        return [{
            values: sin,
            key: "S",
            color: "#ff7f0e"
        }];
    }

    </script>
</body>

SportsPrediction_NW_Baseball/src/SportsPrediction_NW_Baseball/Views/Home/construction.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1 style="text-align:center">Page is Under Construction!!</h1>